services:
  db:
    image: mariadb:10.11
    container_name: blog-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog123
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mariadb", "-u", "blog", "-pblog123", "-e", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    container_name: blog-backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/blog?useUnicode=true&characterEncoding=utf8mb4&serverTimezone=Asia/Shanghai
      SPRING_DATASOURCE_USERNAME: blog
      SPRING_DATASOURCE_PASSWORD: blog123
      APP_JWT_SECRET: "Y29vbC1ibG9nLWp3dC1zZWNyZXQta2V5LWZvci1ibG9nLWFwcC0yMDI2LXByb2R1Y3Rpb24t"
      APP_MAIL_FROM: 1262400013@qq.com
      APP_BLOG_URL: http://localhost
      SPRING_MAIL_HOST: smtp.qq.com
      SPRING_MAIL_PORT: 587
      SPRING_MAIL_USERNAME: 1262400013@qq.com
      SPRING_MAIL_PASSWORD: qauswnreuxwkjbbb
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
      SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
    ports:
      - "19999:8080"

  frontend:
    build: ./frontend
    container_name: blog-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  mysql-data:
